### ISSUE TITLE
Create helpful documentation

### ISSUE THREAD

**Issue by heavybeard** [spinningarrow/zoom-vanilla.js#10]
Create an helpfull documentation for functionality integrations and data attributes usations.

Use comments on scripts and css for explanations

**Comment by spinningarrow** [comment]
Do you mean documentation as in on the README.md or the wiki, or program comments in the `zoom.js` source file?

**Comment by heavybeard** [comment]
I mean everythings :smiley: 

* A README.md for presentation like an landing page for linking to Wiki
* Comments on sources for explanations.
* Add a gulp (or grunt, or both) in order to minimize sources for distributions.

Soon I will start a new branch only for these

**Comment by spinningarrow** [comment]
Nice!

From my side, yes to the first two, but no to the last :tongue: 

Check out `package.json` for the simple build script I wrote which can be invoked by doing `npm run build`. Keeping it simple once again ;)

**Comment by heavybeard** [comment]
Ahahaha perfect!

**Comment by heavybeard** [comment]
Hi @spinningarrow,
yesterday I started the new branch https://github.com/spinningarrow/zoom-vanilla.js/tree/refactoring

In next days I'll write the README.md
