### ISSUE TITLE
Improve the code

### ISSUE THREAD

**Issue by spinningarrow** [spinningarrow/zoom-vanilla.js#13]
@heavybeard you mentioned on #7 that you would like to optimize the code. Let's discuss that here.

On the one hand, I agree because the current code is rather messy/non-traditional but on the other hand right now it maps very closely to the original code on the upstream repo.

With improved code, we'll have ... improved code but it might get more difficult to consume upstream changes.

What do you think?

**Comment by heavybeard** [comment]
Yeah, this is the crucial point.

In my head I think that is a good idea to turn off with original code because we are more active than it (the new video feature can be an evidence).

But I understand that you started this vanilla branch with the README.md purpose:
> This version does not depend on jQuery. I'm also trying not to modify the original code too much so that consuming upstream changes (if any) becomes easier. 

So, is a good idea start a new branch or a new repo?

**Comment by heavybeard** [comment]
I started a new branch https://github.com/spinningarrow/zoom-vanilla.js/issues/10#issuecomment-174300155 with code refactoring

**Comment by spinningarrow** [comment]
Thanks - I took a look at the `refactoring` branch, which includes various changes: moving files to a new folder structure, the addition of Sass, including Bower, JSDoc documentation in the main js file, and so on. It's a good effort but ultimately I think it's taking this project in a direction different to the original intention. I would just like this to be a simple library with a small codebase and as little overhead as possible. 

Perhaps as you mentioned in your previous comment (https://github.com/spinningarrow/zoom-vanilla.js/issues/13#issuecomment-172908947), it might be better for those to be placed in a new fork?

**Comment by heavybeard** [comment]
Now on my fork https://github.com/heavybeard/zoom-vanilla.js there's the refactoring branch, so we can remove it from this fork.

**Comment by spinningarrow** [comment]
Sounds good, thanks!
