### ISSUE TITLE
gh-pages link to script is wrong

### ISSUE THREAD

**Issue by spinningarrow** [spinningarrow/zoom-vanilla.js#2]
-.-

EDIT: On master too, actually.

**Comment by spinningarrow** [comment]
@heavybeard Hey thanks for pitching in - appreciate it! Could you add the commit id in which it was fixed?

**Comment by heavybeard** [comment]
Hi @spinningarrow I made a mistake, sorry. I reopen it!
With master you referred on the original zoom.js?

**Comment by spinningarrow** [comment]
No worries, it happens!

I think my original description is really un-descriptive haha. The issue is that in the `index.html` file on this repo, there's a `script` tag in the end which should point to the script in the dist folder but it's currently pointing to `dist/index.html`. The issue is present on the `gh-pages` and `master` branches in this repo.

**Comment by heavybeard** [comment]
Aaaah ok! In fact your demo doesn't work
http://spinningarrow.github.io/zoom-vanilla.js/

I'll fix it :)

**Comment by spinningarrow** [comment]
Exactly, because it can't find the path to the script (whoops).

Thanks once again!

On Wednesday, 9 December 2015, Andrea Cognini <notifications@github.com>
wrote:

> Aaaah ok! In fact your demo doesn't work
> http://spinningarrow.github.io/zoom-vanilla.js/
>
> I'll fix it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spinningarrow/zoom-vanilla.js/issues/2#issuecomment-163154189>
> .
>


-- 
—Sahil

**Comment by heavybeard** [comment]
I've pushed on master (id 68cf985452e8524e1b26e365c27c3c66d1bb3d46).

What's different on gh-pages? I've seen only my modified files, so you can try a merge.

**Comment by heavybeard** [comment]
With the merge from master branch i've fix it

https://github.com/spinningarrow/zoom-vanilla.js/pull/7
