### ISSUE TITLE
Remove the "style" attribute on the unzoomed image

### ISSUE THREAD

**Issue by Ilshidur** [spinningarrow/zoom-vanilla.js#21]
I recently noticed when zooming on an image and then unzooming that there's a residual "style" attribute on the image :

<img src="http://i.imgur.com/LMcgL0q.jpg">

This can be annoying when trying to change the width of the picture using CSS (e.g. : responsive design).

**Comment by spinningarrow** [comment]
Hi @Ilshidur, thanks for raising this issue! I'll look into it shortly and update here once I have a fix.
