### ISSUE TITLE
Cannot read 'addEventListener' of null

### ISSUE THREAD

**Issue by adehner** [spinningarrow/zoom-vanilla.js#22]
I'm getting an Uncaught TypeError: Cannot read 'addEventListener' of null (line 2 of zoom-vanilla.min.js and line 20 of zoom-vanilla.js) and the zoomed image is not opening. 

Any idea why this is happening?

**Comment by spinningarrow** [comment]
Could you post a CodePen (or equivalent) of the code that's causing this to happen?

**Comment by spinningarrow** [comment]
[Line 20](https://github.com/spinningarrow/zoom-vanilla.js/blob/gh-pages/js/zoom-vanilla.js#L20) adds an event listener to `document.body`, which should surely not be null in a browser.

**Comment by spinningarrow** [comment]
Ah this might be it - are you adding the script inside `<head>` or before the closing `</body>` tag? It needs to be the latter.

**Comment by adehner** [comment]
That was it! Thanks so much.

**Comment by spinningarrow** [comment]
No problem. I think it's worth adding that to the readme - I'll do that now.
