### ISSUE TITLE
Blur Image On Desktop Chrome browsers

### ISSUE THREAD

**Issue by ocordova** [spinningarrow/zoom-vanilla.js#23]
The zoomed image looks blurry on Chrome Desktop even when using a high quality image. No issue with Firefox or Edge.

**Comment by spinningarrow** [comment]
Thanks for opening this. I've heard mention of this bug before but had no luck reproducing it. Could you provide some more information (such as your platform/browser version) or even better - a CodePen example where you see this happening?

**Comment by ocordova** [comment]
I realized that there are also some opened issues in fat's repo... You can reproduce it by opening your demo page (or fat's)  with Chrome on a Desktop. I've tested it in **Windows w/ Chrome 54.0.2840.34 (64-bit)** and **macOS Sierra v10.12 w/ Chrome 53.0.2785.116 (64-bit)**

Perhaps it is imperceptible for photographs, but images with text make it difficult to read.
![issue](https://cloud.githubusercontent.com/assets/694736/18791351/fae9900e-8177-11e6-86da-4a69d7b911ce.png)

**Comment by spinningarrow** [comment]
Oddly enough, I'm still not seeing this (tried with a textual image). I don't doubt it's happening; I'd just like to reproduce it so I can be sure I've fixed it once I change the code.

**Comment by spinningarrow** [comment]
These are the images I tried - can you check if you see any blurriness with them?

### Image 1
<img width="676" alt="screen" src="https://cloud.githubusercontent.com/assets/1797328/18838678/db17283e-843a-11e6-952a-dba49206e8cc.png">

### Image 2
<img width="718" alt="screen2" src="https://cloud.githubusercontent.com/assets/1797328/18838679/db18d9a4-843a-11e6-98db-5c7b34fc616b.png">

### Image 3
![texty](https://cloud.githubusercontent.com/assets/1797328/18838680/db1b6106-843a-11e6-9fa2-59a561613a8a.gif)

Also can I have the following information:
1. What is your display size and resolution?
2. Does changing your browser window's size have any effect on the blurriness?

**Comment by marathia** [comment]
None of the CSS solutions suggested here and elsewhere worked for me, but this did: in zoom-vanilla.js (lines 189, 189) replace:

`var translateY = viewportY - imageCenterY`
`var translateX = viewportX - imageCenterX`

with:

`var translateY = Math.round(viewportY - imageCenterY)`
`var translateX = Math.round(viewportX - imageCenterX)`

(inspired on [this PR](https://github.com/fat/zoom.js/pull/52/commits/94fa559883f76d905473bbff8ce9259b54072f73) for fat/zoom.js)

**Comment by spinningarrow** [comment]
@ocordova @marathia I've applied that change ^ in the latest commit. If you have the time, can you test if it fixes the issue? Thank you (and apologies for the long delay in getting this out)!

Uses the change from https://github.com/fat/zoom.js/pull/52

**Comment by marathia** [comment]
@ spinning arrow This indeed fixes the blurriness, thanks!

**Comment by spinningarrow** [comment]
Awesome, closing this 💯
