### ISSUE TITLE
zoom-img-wrap repositions incorrectly in Firefox 49.0.1

### ISSUE THREAD

**Issue by collnwalkr** [spinningarrow/zoom-vanilla.js#24]
**My setup:** Firefox 49.0.1, MacBook Pro 10.10.5

**Issue:** When zooming on image, the `zoom-img-wrap` div incorrectly  repositions itself too far down the page. It seems that this behavior is dependent on the scroll position. Here are some images showcasing this bug. Each of these are a series of before and after shots. The first image is where I am in the demo page scroll wise, the second is the transformation of the div after zooming on image.

**Scroll position at top of page (behaves correctly)**
<img width="1506" alt="screen shot 2016-10-08 at 1 31 57 pm" src="https://cloud.githubusercontent.com/assets/7200683/19215795/94234e78-8d5c-11e6-8e27-b2ff321985ce.png">
<img width="1506" alt="screen shot 2016-10-08 at 1 32 23 pm" src="https://cloud.githubusercontent.com/assets/7200683/19215796/9423856e-8d5c-11e6-9b0a-2f4ccbe9ebf4.png">

**After scrolling down a bit, thinks get a little wonky**
<img width="1506" alt="screen shot 2016-10-08 at 1 32 40 pm" src="https://cloud.githubusercontent.com/assets/7200683/19215799/942727f0-8d5c-11e6-87df-bb953f3c8ae3.png">
<img width="1506" alt="screen shot 2016-10-08 at 1 32 54 pm" src="https://cloud.githubusercontent.com/assets/7200683/19215797/94243040-8d5c-11e6-9c13-c8a5e4e681f1.png">

**Near the bottom of the page, the image is completely offscreen**
<img width="1506" alt="screen shot 2016-10-08 at 1 33 21 pm" src="https://cloud.githubusercontent.com/assets/7200683/19215800/94285652-8d5c-11e6-9346-edb3a78ad75d.png">
<img width="1506" alt="screen shot 2016-10-08 at 1 33 31 pm" src="https://cloud.githubusercontent.com/assets/7200683/19215798/94245228-8d5c-11e6-8e38-75d691cceda4.png">

**Comment by collnwalkr** [comment]
Just as I expected, the underlying issue is found in the [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect): 
> The amount of scrolling that has been done of the viewport area (or any other scrollable element) is taken into account when computing the bounding rectangle. This means that the rectangle's boundary edges (top, left, bottom, and right) change their values every time the scrolling position changes (because their values are relative to the viewport and not absolute).

I've been able to verify that this bug is due to the aforementioned viewport scrolling quirk through debugging. I'm working on a fix now that will probably be in line with Mozilla's suggested fix:
> If you need the bounding rectangle relative to the top-left corner of the document, just **add the current scrolling position to the top and left properties** (these can be obtained using window.scrollX and window.scrollY) to get a bounding rectangle which is independent from the current scrolling position.

**Comment by collnwalkr** [comment]
Turns out it was a pretty easy fix. The reason rect.top was not calculated correctly was due to `document.body.scrollTop` [not playing nicely with some browsers](https://miketaylr.com/posts/2014/11/document-body-scrolltop.html)

**Chrome**
<img width="1549" alt="screen shot 2016-10-08 at 3 14 24 pm" src="https://cloud.githubusercontent.com/assets/7200683/19216276/fe086988-8d69-11e6-9a73-679507d205fa.png">

**Firefox**
<img width="1552" alt="screen shot 2016-10-08 at 3 14 32 pm" src="https://cloud.githubusercontent.com/assets/7200683/19216277/020131fa-8d6a-11e6-9944-7fbb79455e8f.png">

I found [this fix](http://stackoverflow.com/a/28633515) and have tested it for:
- Chrome 53.0.2785.143
- Safari 10.0
- Firefox 49.0.1
and it seems to work really well. I will make a PR soon with this fix.

**Comment by spinningarrow** [comment]
Sorry for the lack of responses, and thanks for the detailed report! I'll get back to once I've done some investigation, though it might be a while since I'm going on vacation for a week.

**Comment by spinningarrow** [comment]
Once again, thanks for the great effort. Your fix looked good, and I have merged it in.
