### ISSUE TITLE
IE 11 has several issues about opened photo's position

### ISSUE THREAD

**Issue by heavybeard** [spinningarrow/zoom-vanilla.js#26]
There's some issues on Internet Explorer 11.187.14393.0
- When you are on top of the page (y = 0), the image open in this way
  ![image](https://cloud.githubusercontent.com/assets/12038447/19218961/55cd3c50-8e07-11e6-9e91-8b4957f31c58.png)
- On a specific area the image open where you expect it
  ![image](https://cloud.githubusercontent.com/assets/12038447/19219051/344675a4-8e09-11e6-9e88-271d0e391930.png)
- After one scroll yhe image open over the top of the browser
  ![image](https://cloud.githubusercontent.com/assets/12038447/19219058/68f6f44a-8e09-11e6-8594-b4df0421a4f5.png)

I can't provide a video right now.

The https://github.com/spinningarrow/zoom-vanilla.js/pull/25 PR seems to fix it in part.

**Comment by spinningarrow** [comment]
Thanks for the analysis! Will get back once I've done some further investigation.

**Comment by marathia** [comment]
If anyone found a solution for this, please share it...

**Comment by spinningarrow** [comment]
Okay, so I just got IE on a VM and I'm looking at this issue.

@marathia @heavybeard from what I can see, basically the zoomed image doesn't move and essentially opens in the same place as the original image, but with different dimensions. Is this observation correct?

**Comment by spinningarrow** [comment]
I've pushed a fix for this. Can you please check if the latest version works fine on IE? The VM I have is super slow and I'm unable to test fully in it. Besides the position, if you could also check the behaviour for dismissal when scrolling, and clicking with the Ctrl key pressed - I would be super thankful!

**Comment by heavybeard** [comment]
I'll try it. It's been so long that can not remember

**Comment by spinningarrow** [comment]
> It's been so long that can not remember

I'm sorry 🙈

**Comment by heavybeard** [comment]
Now works perfectly!!!

**Comment by spinningarrow** [comment]
Yay!

Once I get confirmation that the other bugs have been fixed, I'll make a release 💯
