### ISSUE TITLE
Unable to use with webpack

### ISSUE THREAD

**Issue by meleyal** [spinningarrow/zoom-vanilla.js#27]
The `package.json` states the main entry as `js/zoom-vanilla.js`, but the `js` dir is ignored in `.npmignore` so it doesn't exist when pulling it from npm.

**Comment by meleyal** [comment]
Managed to solve it with:

```js
resolve: {
  alias: {
    zoom: path.resolve(__dirname, 'node_modules/zoom-vanilla.js/dist/zoom-vanilla.min.js')
  }
},
```

**Comment by spinningarrow** [comment]
Ah, that's interesting. `js/zoom-vanilla.js` the main file for development but `dist/zoom-vanilla.min.js` is the main file for distribution. Does webpack look only at the main entry in package.json?

**Comment by spinningarrow** [comment]
After some thought, I think pointing `main` to `dist/zoom-vanilla.min.js` makes the most sense.
