### ISSUE TITLE
add cursor: zoom-in and cursor: zoom-out

### ISSUE THREAD

**Issue by marathia** [spinningarrow/zoom-vanilla.js#28]
Please consider adding `cursor: zoom-in;` and `cursor: zoom-out;` to zoom.css, especially for Edge that only supports the unprefixed versions (see [http://caniuse.com/#feat=css3-cursors-newer](http://caniuse.com/#feat=css3-cursors-newer)).

**Comment by spinningarrow** [comment]
I don't mind at all. Would you perhaps have the bandwidth to make a pull request for this change?

**Comment by spinningarrow** [comment]
Fixed by incorporating [autoprefixer][] in the build chain.

[autoprefixer]: https://github.com/postcss/autoprefixer
