### ISSUE TITLE
About zoom out when  is big

### ISSUE THREAD

**Issue by doublnt** [spinningarrow/zoom-vanilla.js#31]
The image is like this below 
> ![](http://images2015.cnblogs.com/q/161654/201705/161654-20170523223607857-1679571871.jpg)

When I use the scripts, It doesn't work. The image will zoom in when I click the image.
How should I modified to apply this  in such big image in my project?

**Comment by spinningarrow** [comment]
@doublnt Which browser is this in? And if possible can you create a codepen/jsfiddle/some live example where I can test this?

**Comment by doublnt** [comment]
I use another way (open new page  ) to show my image
