### ISSUE TITLE
Slick Carousel and Vanilla Zoom

### ISSUE THREAD

**Issue by cwahlfeldt** [spinningarrow/zoom-vanilla.js#32]
This might be a long shot but I cant seem to get this to work within a slick carousel. Has anyone gotten slick carousel and zoom to work? Or any slider + zoom configuration to work?

The issues seem to be stemming from the dispose function not being called at all?

**Comment by spinningarrow** [comment]
@cwahlfeldt I haven’t used slick carousel before - can you link to it?

Or even better - it would be super helpful if you could make a quick codepen or jsfiddle example with the carousel and vanilla zoom to help me debug.

**Comment by cwahlfeldt** [comment]
Hey @spinningarrow Thanks for getting back to me - I made a codepen to check out. https://codepen.io/cwahlfeldt/pen/YxLMGP

**Comment by spinningarrow** [comment]
I think it has something to do with the styles slick applies to the images. There's a class called `slick-side` which sets `display: none` causing the zoomed image to disappear.

**Comment by spinningarrow** [comment]
Hi @cwahlfeldt since this seems to be an issue with a different third party plugin, I'm closing this issue. Feel free to reopen if you feel it should be fixed in zoom-vanilla.js though!
