### ISSUE TITLE
Way to limit max width?

### ISSUE THREAD

**Issue by ezetojo** [spinningarrow/zoom-vanilla.js#37]
I tried using css to limit the size but its calculated using css transform-scale...

any idea?

i also tried editing the js but i don't get it all. all i did was set the scale formula to half, but itsnt cool in mobile.

thanks in advance

pd. full-width scale the image to large for my... so i want to set a max width (kinda 1000px) on desktop to the img.

**Comment by spinningarrow** [comment]
I've created a codepen with what I think is the desired behaviour here: https://codepen.io/spinningarrow/pen/aqEaEQ

Essentially, I've modified the `calculateZoom` function to add a check for a maximum width. Refer to lines 188-194 of the JS in the pen.

This way, the image will not scale up beyond 1000px. Is this how you intended it to behave?

**Comment by ezetojo** [comment]
@spinningarrow thanks! that's what i was trying to do!
