### ISSUE TITLE
Using this with dynamically loaded vue images?

### ISSUE THREAD

**Issue by johnpyp** [spinningarrow/zoom-vanilla.js#38]
Does this work with dynamically loaded images/dom?

Also, is it possible to make it usable with import statements in vue/react?

**Comment by spinningarrow** [comment]
Yes, it should work with dynamically loaded images. 

For your second query - I’m not sure as I haven’t tried it before. Are you facing any issues with that approach?

**Comment by spinningarrow** [comment]
I've tested it by importing it with webpack in a React project, and added a note to the README for the import statements needed.
