### ISSUE TITLE
Demo not working correctly on Chrome

### ISSUE THREAD

**Issue by jstnbr** [spinningarrow/zoom-vanilla.js#6]
Hi,

The demo page is not working correctly on Chrome 47.0.2526.106.  I'm not sure what extra information I should provide here except for the fact that I am clicking on an image and nothing is happening.  Is the demo page working for you?  And on what browser?

Thank you,
Justin

**Comment by heavybeard** [comment]
Hi Justin,
can you try it now?

Andrea

**Comment by jstnbr** [comment]
Hey @heavybeard ,
I will check tomorrow morning and let you know.  I am away from that PC now, but I'm happy to see it's working on my Macbook Safari 8.0.8.

Thanks,
Justin

**Comment by heavybeard** [comment]
Perfect :)
Your issue is relative to this https://github.com/spinningarrow/zoom-vanilla.js/issues/2 and today I fixed on `gh-pages` branch - from `master` branch.

Be careful: the minimized version is not updated

**Comment by jstnbr** [comment]
It works!  Thanks for keeping me updated.

**Comment by heavybeard** [comment]
If you notice some bugs, please keep me update
